### ISSUE TITLE
Error when $body is null

### ISSUE THREAD

**Issue by jcRisch** [vinkla/instagram#89] opened 2018-09-03 21:45 UTC
Hello, 
I had this error tonight : 
`Type error: Return value of Vinkla\Instagram\Instagram::get() must be an object, null returned`
I never had it, I think this is due to Instagram rate-limiting (big traffic today).

To solve the issue, I had to re-write the $`instagram->media()` method and test if `$body` is `null` or not. 
If `$body` is `null`, I return `null`; If not I return `$body->data`

Is that a known issue ? 
If not, it could be good to add a if statement into the `$instagram->get()` method or change the visibility of the `$instagram->get()` method from `protected` to `public`.

Thank you,

**Comment by vinkla** [comment] 2018-09-04 06:58
> I never had it, I think this is due to Instagram rate-limiting (big traffic today).

Yes, I believe so. Are you using the latest version of this package?

**Comment by jcRisch** [comment] 2018-09-04 08:06
Yes. 
I modified src/Instagram.php at line 81
From  
`return $response->data;`
To
`if ($response) { return $response->data;} else { return null;}`

**Comment by vinkla** [comment] 2018-09-05 12:14
Hmm, if this would be a rate-limit issue the Instagram API should return an error response. What can I do to test this issue?

**Comment by jcRisch** [comment] 2018-09-05 12:30
Unfortunatly, I don't know how to reproduce the error. It happened only few minutes.
Maybe when  `$this->httpClient->sendRequest($request);` fails, it returns null. The response should be tested to avoid crashing the website when calling to an attribute of the response ($body->data).

Same issue as https://github.com/vinkla/instagram/issues/75 ?

**Comment by vinkla** [comment] 2018-09-05 15:42
> Maybe when `$this->httpClient->sendRequest($request);` fails, it returns null.

Not sure when or if this could happen. I'll go ahead and close this issue and if you are able to reproduce this issue, please get in touch.

> Same issue as #75 ?

I don't think this is related to #75 since we [catch all errors](https://github.com/vinkla/instagram/commit/ca25c21855396c3ad9e26e30b2c6556586b0ec93) sent from Instagram. The Instagram should always return an error message.

**Closed by vinkla** 2018-09-05 15:42 UTC
Labels: bug
